export const mockTabkeData = [
    {
      key: '1',
      name: 'John Brown',
      age: 11,
      address: 'New York No. 1 Lake Park',
      date: '06/20/2022',
      zone: 100,
      region: 'Depot',
      dispatchGroupTime: '04:50 AM',
      truckDispatchTime: '5:30 AM',
      truckEndTime: '12:00 PM',
      pretripTime: '00:00',
      serviceType: 'A',
      description: 'My name is John Brown, I am 32 years old, living in New York No. 1 Lake Park.',
    },{
      key: '2',
      name: 'Jim Green',
      age: 44,
      address: 'London No. 1 Lake Park',
      date: '06/20/2022',
      zone: 110,
      region: 'Depot',
      dispatchGroupTime: '04:50 AM',
      truckDispatchTime: '5:30 AM',
      truckEndTime: '12:00 PM',
      pretripTime: '00:00',
      serviceType: 'A',
      description: 'My name is John Brown, I am 32 years old, living in New York No. 1 Lake Park.',
    },{
      key: '3',
      name: 'Joe Black',
      age: 55,
      address: 'Sidney No. 1 Lake Park',
      date: '06/20/2022',
      zone: 123,
      region: 'Depot',
      dispatchGroupTime: '04:50 AM',
      truckDispatchTime: '5:30 AM',
      truckEndTime: '12:00 PM',
      pretripTime: '00:00',
      serviceType: 'C',
      description: 'My name is John Brown, I am 32 years old, living in New York No. 1 Lake Park.',
    },{
      key: '4',
      name: 'Jim Red',
      age: 33,
      address: 'London No. 2 Lake Park',
      date: '06/20/2022',
      zone: 211,
      region: 'Depot',
      dispatchGroupTime: '04:50 AM',
      truckDispatchTime: '5:30 AM',
      truckEndTime: '12:00 PM',
      pretripTime: '00:00',
      serviceType: 'A'
    },{
      key: '5',
      name: 'Apple Tree',
      age: 22,
      address: '123 main st. NJ 012345',
      date: '06/20/2022',
      zone: 212,
      region: 'Depot',
      dispatchGroupTime: '04:50 AM',
      truckDispatchTime: '5:30 AM',
      truckEndTime: '12:00 PM',
      pretripTime: '00:00',
      serviceType: 'B'
    },{
      key: '6',
      name: 'Banana Root',
      age: 12,
      address: '456 columnbia dr. NJ 112233',
      date: '06/20/2022',
      zone: 300,
      region: 'Depot',
      dispatchGroupTime: '04:50 AM',
      truckDispatchTime: '5:30 AM',
      truckEndTime: '12:00 PM',
      pretripTime: '00:00',
      serviceType: 'B'
    },{
      key: '7',
      name: 'Orange Hill',
      age: 45,
      address: '789 river road NJ 445566',
      date: '06/20/2022',
      zone: 300,
      region: 'Depot',
      dispatchGroupTime: '04:50 AM',
      truckDispatchTime: '5:30 AM',
      truckEndTime: '12:00 PM',
      pretripTime: '00:00',
      serviceType: 'A'
    },{
        key: '8',
        name: 'Milk Tea',
        age: 25,
        address: '111 river road NJ 121212',
        date: '06/20/2022',
        zone: 300,
        region: 'Depot',
        dispatchGroupTime: '04:50 AM',
        truckDispatchTime: '5:30 AM',
        truckEndTime: '12:00 PM',
        pretripTime: '00:00',
        serviceType: 'A'
      },{
        key: '9',
        name: 'Coca Cola',
        age: 15,
        address: '789 Rodak road NJ 123321',
        date: '06/20/2022',
        zone: 300,
        region: 'Depot',
        dispatchGroupTime: '04:50 AM',
        truckDispatchTime: '5:30 AM',
        truckEndTime: '12:00 PM',
        pretripTime: '00:00',
        serviceType: 'A'
      },{
        key: '10',
        name: 'Coffee Bottle',
        age: 5,
        address: '123 Fenway NJ 555666',
        date: '06/20/2022',
        zone: 300,
        region: 'Depot',
        dispatchGroupTime: '04:50 AM',
        truckDispatchTime: '5:30 AM',
        truckEndTime: '12:00 PM',
        pretripTime: '00:00',
        serviceType: 'A'
      },{
        key: '11',
        name: 'Mango Juice',
        age: 33,
        address: '42 Milk way NJ 333444',
        date: '06/20/2022',
        zone: 300,
        region: 'Depot',
        dispatchGroupTime: '04:50 AM',
        truckDispatchTime: '5:30 AM',
        truckEndTime: '12:00 PM',
        pretripTime: '00:00',
        serviceType: 'A'
      },{
        key: '12',
        name: 'Grape Sea',
        age: 22,
        address: '1 Freshdirect Dr. NJ 111222',
        date: '06/20/2022',
        zone: 300,
        region: 'Depot',
        dispatchGroupTime: '05:50 AM',
        truckDispatchTime: '5:30 AM',
        truckEndTime: '12:00 PM',
        pretripTime: '00:00',
        serviceType: 'B'
      },{
        key: '13',
        name: 'Watermelon Park',
        age: 12,
        address: '98 river road NJ 445566',
        date: '06/20/2022',
        zone: 300,
        region: 'Depot',
        dispatchGroupTime: '04:50 AM',
        truckDispatchTime: '5:30 AM',
        truckEndTime: '12:00 PM',
        pretripTime: '00:00',
        serviceType: 'A'
      },
  ];